package tests;

import org.junit.Test;
import org.openqa.selenium.Cookie;
import utilities.TestBase;

import java.util.Set;

public class Day09_Cookies extends TestBase {
    /*
    Cookies are temporary files that is generated by the browsers.
    It's a way for a website to remember you, your preferences, and your habits online.
     */

    //-Go to amazon  and automate the tasks:
    //1. Find the total number of cookies
    //2. Print all the cookies
    //3. Get the cookies by their name
    //4. Add new cookie
    //5. Delete cookie by name
    //6. Delete all the cookies

    @Test
    public void cookieTest() throws InterruptedException {
        //-Go to amazon  and automate the tasks:
        driver.get("https://www.amazon.com");

        //1. Find the total number of cookies
        Thread.sleep(2000);
        Set<Cookie> allCookies = driver.manage().getCookies();
        int numOfCookies = allCookies.size();
        System.out.println("Number of Cookies : " + numOfCookies);

        //2. Print all the cookies
        for(Cookie eachCookie : allCookies){
            System.out.println("Cookie ==>>> " + eachCookie);
            System.out.println("Cookie Value ==>>> " + eachCookie.getValue());
            System.out.println("Cookie Name ==>>> " + eachCookie.getName());
        }

        //3. Get the cookies by their name
        System.out.println("Cookie Named : " + driver.manage().getCookieNamed("i18n-prefs"));//this will return  value of the cookie (skin ==>>> name of cookie)
                                                                                             //entering cookie name and getting th entire cookie

        //4. Add new cookie
        Cookie newCookie = new Cookie("my-favorite-cookie", "apple-pie");
        driver.manage().addCookie(newCookie);
        Set<Cookie> newCookies = driver.manage().getCookies();
        System.out.println("New Number Of Cookies ==>>> " + newCookies.size());//1 more than original number of cookie

        //5. Delete cookie by name
        driver.manage().deleteCookieNamed("my-favorite-cookie");
        int lastNumberOfCookies = driver.manage().getCookies().size();
        System.out.println("Last Number Of Cookies ==>>> " + lastNumberOfCookies);

        //6. Delete all the cookies
        driver.manage().deleteAllCookies();
        Thread.sleep(2000);
        int finalNumberOfCookies = driver.manage().getCookies().size();
        System.out.println("Final Number of Cookies ==>>> " + finalNumberOfCookies);



    }
}
